[package]
name = "shasper"
version = "0.1.0"
authors = ["Parity Team <admin@parity.io>"]

[workspace]
members = [
	"runtime",
	"executor",
	"util/ssz",
	"util/ssz-derive",
	"util/shuffling",
]
exclude = [
	"runtime/wasm",
]
